# Generated by Django 5.1.1 on 2024-09-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainput',
            name='sent_date',
            field=models.DateField(auto_now=True),
        ),
    ]
